name: tugas_akhir_valorant
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  crypto: ^3.0.6
  cupertino_icons: ^1.0.8
  encrypt: ^5.0.3
  flutter:
    sdk: flutter
  flutter_local_notifications: ^19.5.0
  flutter_secure_storage: ^9.2.4
  geolocator: ^14.0.2
  google_fonts: ^6.2.1
  http: ^1.5.0
  intl: ^0.20.2
  path: ^1.9.1
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  geocoding: ^4.0.0
  sqflite: ^2.4.2

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/

  fonts:
    - family: Rajdhani
      fonts:
        - asset: assets/fonts/Rajdhani-Regular.ttf
        - asset: assets/fonts/Rajdhani-Bold.ttf
          weight: 700
        - asset: assets/fonts/Rajdhani-SemiBold.ttf
          weight: 600
    - family: Tungsten
      fonts:
        - asset: assets/fonts/Tungsten-Bold.ttf
    - family: Valorant
      fonts:
        - asset: assets/fonts/Valorant-Font.ttf
